name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      # NOTE: DEPLOY_URL must reference the running deployment and be publicly reachable from GitHub Actions runners.
      DEPLOY_URL: ${{ secrets.DEPLOY_URL != '' && secrets.DEPLOY_URL || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Set fallback DEPLOY_URL
        if: ${{ env.DEPLOY_URL == '' }}
        run: echo "DEPLOY_URL=http://127.0.0.1:${PORT}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build

      - name: Show local BUILD_ID (CI)
        run: |
          set -e
          echo 'Local BUILD_ID:'
          cat .next/BUILD_ID
          echo 'Local static assets count:'
          find .next/static -type f | wc -l
          echo 'Local standalone server.js:'
          test -f .next/standalone/server.js && echo 'server.js OK' || (echo 'server.js missing' && exit 1)

      - name: Create deployment archive
        run: |
          set -e
          tar -czf deploy.tgz .next/standalone .next/static .next/BUILD_ID public

      - name: Upload archive via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: deploy.tgz
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Unpack archive on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e
            cd "${{ secrets.DEPLOY_PATH }}"
            rm -rf standalone static BUILD_ID
            tar -xzf deploy.tgz
            rm -f deploy.tgz
            ls -la .next || true


      - name: Verify build artifacts on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e
            cd "${{ secrets.DEPLOY_PATH }}"
            echo 'Listing .next on remote:'
            ls -la .next || true
            echo 'BUILD_ID:'
            cat .next/BUILD_ID
            echo 'Check standalone server.js:'
            test -f .next/standalone/server.js && echo 'server.js OK' || (echo 'server.js missing' && exit 1)
            echo 'Static assets count:'
            find .next/static -type f | wc -l
            echo "Misplaced standalone check:"
            [ -d .next/standalone ] && echo ".next/standalone OK" || echo ".next/standalone MISSING"
            [ -d standalone ] && echo "Found ./standalone (wrong)" || true

      - name: Restart domain via devil (Passenger)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e
            devil www restart gliwicka111.pl

      - name: Preflight deployment configuration
        run: |
          set -euo pipefail
          DEPLOY_URL_VALUE="${DEPLOY_URL:-}"
          PORT_VALUE="${PORT:-}"
          if [ -z "$PORT_VALUE" ]; then
            echo "Preflight: PORT is unset"
          else
            echo "Preflight: PORT='$PORT_VALUE'"
          fi
          if [ -z "$DEPLOY_URL_VALUE" ]; then
            echo "Preflight: DEPLOY_URL is empty"
            echo "ERROR: DEPLOY_URL must be provided before continuing."
            exit 1
          fi
          echo "Preflight: DEPLOY_URL='$DEPLOY_URL_VALUE'"
          if ! printf '%s' "$DEPLOY_URL_VALUE" | grep -Eq '^https?://[^[:space:]]+$'; then
            echo "ERROR: DEPLOY_URL '$DEPLOY_URL_VALUE' is malformed. Expected to start with http:// or https://."
            exit 1
          fi
          if [ -n "$PORT_VALUE" ] && ! printf '%s' "$PORT_VALUE" | grep -Eq '^[0-9]+$'; then
            echo "ERROR: PORT '$PORT_VALUE' must be numeric when set."
            exit 1
          fi

      - name: Wait for service to start
        if: ${{ env.DEPLOY_URL != '' }}
        env:
          PORT: ${{ env.PORT }}
          HOST: 127.0.0.1
          HOSTNAME: 127.0.0.1
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          set -euo pipefail
          export PORT HOST HOSTNAME
          HEALTH_HOST="${HOST:-${HOSTNAME}}"
          HEALTHCHECK_URL="http://${HEALTH_HOST}:${PORT}"
          LOG_FILE=$(mktemp)
          LOCAL_CHECK_PASSED=0

          echo "Starting Next.js server in background on ${HEALTHCHECK_URL}..."
          npm start >"$LOG_FILE" 2>&1 &
          NEXT_PID=$!

          cleanup() {
            STATUS=$?
            trap - EXIT
            if [ -n "${NEXT_PID:-}" ] && kill -0 "$NEXT_PID" 2>/dev/null; then
              echo "Stopping Next.js server (PID: $NEXT_PID)"
              kill "$NEXT_PID" 2>/dev/null || true
              wait "$NEXT_PID" 2>/dev/null || true
            fi
            if [ "$STATUS" -ne 0 ] && [ "${LOCAL_CHECK_PASSED}" -eq 0 ]; then
              echo "---- Next.js server log (last 50 lines) ----"
              tail -n 50 "$LOG_FILE" || true
              echo "-------------------------------------------"
            fi
            exit "$STATUS"
          }

          trap cleanup EXIT

          echo 'Waiting for service to be ready...'
          for i in $(seq 1 10); do
            if curl -fsS "$HEALTHCHECK_URL" >/dev/null 2>&1; then
              echo "Service is up at $HEALTHCHECK_URL."
              LOCAL_CHECK_PASSED=1
              break
            fi

            if ! kill -0 "$NEXT_PID" 2>/dev/null; then
              echo 'Next.js server process exited unexpectedly.'
              exit 1
            fi

            echo "Attempt $i failed; retrying in 5s..."
            sleep 5

            if [ "$i" -eq 10 ]; then
              echo "Service did not respond after $i attempts."
              exit 1
            fi
          done

          echo 'Local Next.js server readiness confirmed.'
          if [ -n "${NEXT_PID:-}" ] && kill -0 "$NEXT_PID" 2>/dev/null; then
            kill "$NEXT_PID" 2>/dev/null || true
            wait "$NEXT_PID" 2>/dev/null || true
            NEXT_PID=""
          fi

          echo "Verifying remote deployment at $DEPLOY_URL"
          REMOTE_CHECK_PASSED=0
          REMOTE_RETRIES=10
          for attempt in $(seq 1 "$REMOTE_RETRIES"); do
            if curl -fsS "$DEPLOY_URL" >/dev/null 2>&1; then
              echo "Remote service is up at $DEPLOY_URL."
              REMOTE_CHECK_PASSED=1
              break
            fi

            echo "Remote attempt $attempt failed; retrying in 5s..."
            if [ "$attempt" -lt "$REMOTE_RETRIES" ]; then
              sleep 5
            fi
          done

          if [ "$REMOTE_CHECK_PASSED" -ne 1 ]; then
            echo "Remote service failed to respond after $REMOTE_RETRIES attempts."
            echo "Attempting to capture remote logs for diagnostics..."
            if [ -n "${DEPLOY_HOST:-}" ] && [ -n "${DEPLOY_USER:-}" ] && [ -n "${DEPLOY_SSH_KEY:-}" ]; then
              SSH_KEY_FILE=$(mktemp)
              printf '%s\n' "$DEPLOY_SSH_KEY" >"$SSH_KEY_FILE"
              chmod 600 "$SSH_KEY_FILE"

              if ssh -o StrictHostKeyChecking=no -i "$SSH_KEY_FILE" "$DEPLOY_USER@$DEPLOY_HOST" <<'EOSSH'
              APP_NAME="gliwicka111"
              if command -v pm2 >/dev/null 2>&1; then
                echo "---- Remote pm2 status ----"
                pm2 status "$APP_NAME" || true
                echo "---- Remote pm2 logs (last 100 lines) ----"
                pm2 logs "$APP_NAME" --lines 100 --nostream || true
              else
                echo "pm2 not found on remote host. Showing recent Node processes:"
                ps -ef | grep node || true
              fi
          EOSSH
              then
                echo "Remote diagnostics collected successfully."
              else
                echo "SSH command failed while collecting remote logs."
              fi

              rm -f "$SSH_KEY_FILE"
            else
              echo "SSH credentials are not fully configured; unable to fetch remote logs."
            fi

            exit 1
          fi

      - name: Smoke test
        if: ${{ env.DEPLOY_URL != '' }}
        run: |
          set -e
          curl -fsSL "$DEPLOY_URL" | grep -qi "<html"
