export const virtualOfficeCopy = {
  pl: {
    title: "Biuro Wirtualne",
    subtitle: "Prestiżowy adres biznesowy od 99 zł/miesiąc",
    description:
      "Uzyskaj profesjonalny adres dla swojej firmy z pełnym wsparciem administracyjnym",
    packages: {
      basic: {
        name: "Pakiet Podstawowy",
        price: "99 zł/miesiąc",
        features: [
          "Adres do rejestracji firmy",
          "Odbiór korespondencji",
          "Powiadomienia SMS/email",
        ],
      },
      standard: {
        name: "Pakiet Standard",
        price: "149 zł/miesiąc",
        features: [
          "Wszystko z pakietu podstawowego",
          "Przekazywanie połączeń",
          "2h sali konferencyjnej/miesiąc",
          "Skanowanie dokumentów",
        ],
      },
      premium: {
        name: "Pakiet Premium",
        price: "249 zł/miesiąc",
        features: [
          "Wszystko z pakietu standard",
          "Dedykowany numer telefonu",
          "5h sali konferencyjnej/miesiąc",
          "Obsługa sekretarska",
          "Magazynowanie dokumentów",
        ],
      },
    },
    fields: {
      firstName: "Imię",
      lastName: "Nazwisko",
      email: "Adres email",
      phone: "Numer telefonu",
      companyName: "Nazwa firmy",
      nip: "NIP (opcjonalnie)",
      businessType: "Typ działalności",
      package: "Wybierz pakiet",
      startDate: "Data rozpoczęcia",
      additionalServices: "Usługi dodatkowe",
      message: "Dodatkowe informacje",
      gdprConsent: "Wyrażam zgodę na przetwarzanie moich danych osobowych",
      marketingConsent:
        "Wyrażam zgodę na otrzymywanie informacji marketingowych",
    },
    businessTypes: {
      "sole-proprietorship": "Działalność gospodarcza",
      llc: "Spółka z o.o.",
      corporation: "Spółka akcyjna",
      other: "Inne",
    },
    additionalServicesList: [
      "Dodatkowe godziny sali konferencyjnej",
      "Obsługa księgowa",
      "Doradztwo prawne",
      "Tłumaczenia",
      "Usługi kurierskie",
      "Magazynowanie dokumentów",
    ],
    submit: "Wyślij zapytanie",
    submitting: "Wysyłanie...",
  },
  en: {
    title: "Virtual Office",
    subtitle: "Prestigious business address from 99 PLN/month",
    description:
      "Get a professional address for your company with full administrative support",
    packages: {
      basic: {
        name: "Basic Package",
        price: "99 PLN/month",
        features: [
          "Company registration address",
          "Mail collection",
          "SMS/email notifications",
        ],
      },
      standard: {
        name: "Standard Package",
        price: "149 PLN/month",
        features: [
          "Everything from basic package",
          "Call forwarding",
          "2h conference room/month",
          "Document scanning",
        ],
      },
      premium: {
        name: "Premium Package",
        price: "249 PLN/month",
        features: [
          "Everything from standard package",
          "Dedicated phone number",
          "5h conference room/month",
          "Secretary service",
          "Document storage",
        ],
      },
    },
    fields: {
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email Address",
      phone: "Phone Number",
      companyName: "Company Name",
      nip: "Tax ID (optional)",
      businessType: "Business Type",
      package: "Choose Package",
      startDate: "Start Date",
      additionalServices: "Additional Services",
      message: "Additional Information",
      gdprConsent: "I consent to the processing of my personal data",
      marketingConsent: "I consent to receiving marketing information",
    },
    businessTypes: {
      "sole-proprietorship": "Sole Proprietorship",
      llc: "Limited Liability Company",
      corporation: "Corporation",
      other: "Other",
    },
    additionalServicesList: [
      "Additional conference room hours",
      "Accounting services",
      "Legal consulting",
      "Translation services",
      "Courier services",
      "Document storage",
    ],
    submit: "Send Inquiry",
    submitting: "Sending...",
  },
} as const;
